title: jupyter-scatter tutorial
author: Friz Lekschas & Trevor Manz
logo: 'images/favicon.svg'
html:
  favicon: "images/favicon.svg"
repository:
    url: "https://github.com/flekschas/jupyter-scatter-tutorial"
